modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = "A valid URL to your issue tracker where people can open bug tickets"
license = "All Rights Reserved"

[[mods]]
modId = "cobbledollars_villagers_overhaul_rca"
version = "${version}"
displayName = "CobbleDollars Villagers Overhaul"
authors = "Streats1"
description = '''
Integrates CobbleDollars with villager trading system
'''
#logoFile = ""

[[dependencies.cobbledollars_villagers_overhaul_rca]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobbledollars_villagers_overhaul_rca]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.182,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobbledollars_villagers_overhaul_rca]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.7.1,)"
ordering = "AFTER"
side = "BOTH"
